Edit Header.jsx with some tailwind classes added
priyankapasrija/To-Do-List-React pull request #3
Opened 2023-09-22 17:42 UTC by lucy444sarah

2023-09-22 17:43 UTC, lucy444sarah commented
Hey,just edited the Header with a couple of tailwind.css classes (ok)

2023-09-24 11:59 UTC, Lukileila requested changes
Contrast on dark green / dark red too low.
Contrast on the Add button too low.
Container too small for text. (Padding could be added)

2023-09-25 11:01 UTC, Lukileila approved these changes

2023-09-25 11:02 UTC, merged

2023-09-25 11:02 UTC, Lukileila commented
¯\_(ツ)_/¯